name: asap
channels:
  - conda-forge/label/cf201901
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py36_0
  - openssl
  - pandas
  - pytz=2019.3=py_0
  - appnope
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_1000
  - freetype
  - graphviz
  - icu
  - importlib_metadata=1.3.0=py36_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipython=7.11.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.2=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=5.1.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - kiwisolver
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx
  - libffi
  - libgfortran
  - liblapack=3.8.0=14_openblas
  - libopenblas
  - libpng
  - libsodium
  - libtiff
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib=3.1.2=py36_1
  - matplotlib-base
  - mistune
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py_1
  - ncurses
  - notebook=6.0.1=py36_0
  - numpy
  - pandoc=2.9.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.3.1=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py_1001
  - pydot=1.4.1=py36_1001
  - pydotplus=2.0.2=pyhd1c1de3_3
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt
  - pyrsistent
  - python
  - python-dateutil=2.8.1=py_0
  - pyzmq
  - qt
  - qtconsole=4.6.0=py_0
  - scikit-learn
  - scipy
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py36_0
  - sip
  - six=1.13.0=py36_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk
  - tornado
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz
  - zeromq
  - zipp=0.6.0=py_0
  - zlib
  - zstd
  - biopython
  - jpeg
  - readline
  - sqlite